// This script has been generated by the auto coder of the website. The original code is in python, in the main.py of this folder.

function clear_screen() {
    let Xs = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4]
    let Ys = [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
    let i = 0
    while (i < 25) {
        led.unplot(Xs[i], Ys[i])
        i = i + 1
    }
}

basic.forever(function on_forever() {
    let Xs: number[];
    let Ys: number[];
    let indice: number;
    if (input.temperature() < 40) {
        clear_screen()
        Xs = [0, 1, 2, 3, 4]
        Ys = [3, 4, 3, 2, 1]
        indice = 0
        while (indice < 5) {
            led.plot(Xs[indice], Ys[indice])
            indice = indice + 1
        }
    } else if (input.temperature() > 40) {
        clear_screen()
        Xs = [0, 2, 4, 0, 2, 4, 0, 2, 4, 0, 2, 4]
        Ys = [0, 0, 0, 1, 1, 1, 2, 2, 2, 4, 4, 4]
        indice = 0
        while (indice < 12) {
            led.plot(Xs[indice], Ys[indice])
            indice = indice + 1
        }
    }
    
})
